version: '3.8'

services:
  client_web:
    container_name: linkit_web-service
    build:
      context: ./src/web/
      dockerfile: DockerfileDev
    ports:
      - "8081:8081"
    volumes:
      - ./src/web:/web_service
      - ./src/shared:/shared
      - web_service_node_modules:/web_service/node_modules
    depends_on:
#      - client_mobile
      - server
    command: >
      bash -c "
      npm install &&
      npm run build &&
      npm run dev
      "

#  client_mobile:
#    container_name: linkit_mobile-service
#    build:
#      context: ./src/web/
#      dockerfile: DockerfileDev
#    volumes:
#      - ./src/web:/web_service
#      - ./src/shared:/shared
#      - mobile_service_node_modules:/web_service/node_modules
#    command: >
#      bash -c "
#      npm install &&
#      npm run build &&
#      cd android &&
#      ./gradlew assembleDebug &&
#      cd .. &&
#      mv android/app/build/outputs/apk/debug/app-debug.apk /web_service/src/ &&
#      echo 'APK generated at /web_service/app-debug.apk'
#      "

  database:
    container_name: linkit_database
    image: mariadb:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app_network

  server:
    container_name: linkit_server
    build:
      context: ./src/server/
      dockerfile: DockerfileDev
    ports:
      - "8080:8080"
    volumes:
      - ./src/server:/server
      - ./src/shared:/shared
      - /server/node_modules
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - app_network

volumes:
  db-data:
  mobile_service_node_modules:
  web_service_node_modules:

networks:
  app_network:
