version: '3.8'

services:
  server:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/area
    depends_on:
      - mongodb
    networks:
      - area_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - area_network

  client_mobile:
    build:
      context: ./src/mobile
      dockerfile: Dockerfile
    volumes:
      - mobile-build:/app/build
    networks:
      - area_network

  client_web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - mobile-build:/app/mobile-build:ro
    depends_on:
      - client_mobile
      - server
    networks:
      - area_network

volumes:
  mobile-build:
  mongodb_data:

networks:
  area_network:
    driver: bridge
