version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - app_network
    command: npm run start:prod
    security_opt:
      - no-new-privileges:true
    user: "node"

  database:
    image: mariadb:latest
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app_network
    expose:
      - "3306"
    security_opt:
      - no-new-privileges:true

volumes:
  db-data:

networks:
  app_network:
    driver: bridge
