name: mirror

on:
  push:

env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-DEV-500-REN-5-1-area-louis.langanay.git

jobs:
  mirror:
    name: Push to mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}